// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Main_Program.Models
{
    public partial class Departments
    {
        public Departments()
        {
            Stores = new HashSet<Stores>();
        }

        public int IdDepartment { get; set; }
        public string TypeDepartment { get; set; }

        public virtual ICollection<Stores> Stores { get; set; }
    }
}