// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Main_Program.Models
{
    public partial class QuantityProdDepartment2Result
    {
        public string ProductName { get; set; }
        public int? Quantity { get; set; }
    }
}
