// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Main_Program.Models
{
    public partial class Requests
    {
        public Requests()
        {
            RequestsProducts = new HashSet<RequestsProducts>();
        }

        public int IdRequest { get; set; }
        public int? SroreАppointment { get; set; }
        public int? StoreSource { get; set; }
        public string? Date { get; set; }

        public virtual Stores SroreАppointmentNavigation { get; set; }
        public virtual Stores StoreSourceNavigation { get; set; }
        public virtual ICollection<RequestsProducts> RequestsProducts { get; set; }
    }
}