// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Main_Program.Models
{
    public partial class RequestsProducts
    {
        public int IdRequestsProducts { get; set; }
        public int? IdRequest { get; set; }
        public int? IdProduct { get; set; }
        public int? Quantity { get; set; }

        public virtual Products IdProductNavigation { get; set; }
        public virtual Requests IdRequestNavigation { get; set; }
    }
}