// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Main_Program.Models
{
    public partial class Stores
    {
        public Stores()
        {
            RequestsSroreАppointmentNavigation = new HashSet<Requests>();
            RequestsStoreSourceNavigation = new HashSet<Requests>();
        }

        public int IdStore { get; set; }
        public int? IdDepartment { get; set; }
        public int? IdUser { get; set; }

        public virtual Departments IdDepartmentNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
        public virtual ICollection<Requests> RequestsSroreАppointmentNavigation { get; set; }
        public virtual ICollection<Requests> RequestsStoreSourceNavigation { get; set; }
    }
}