// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Main_Program.Models
{
    public partial class Users
    {
        public Users()
        {
            Stores = new HashSet<Stores>();
        }

        public int IdUser { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int? IdRole { get; set; }

        public virtual Roles IdRoleNavigation { get; set; }
        public virtual ICollection<Stores> Stores { get; set; }
    }
}